Feature/my past session
NashTech-Labs/go1Percent_Automation pull request #103
Opened 2023-11-16 11:45 UTC by Nituyadav0109

2023-11-16 13:00 UTC, Ritika-gupta20 requested changes
Please resolve the comments

2023-11-16 13:00 UTC, Ritika-gupta20 commented on go1percent/test/Go1PercentAPIAutomation/myPastSession/myPastSession.js
Folder name to be in camel case

2023-11-17 08:28 UTC, Nituyadav0109 commented on go1percent/test/Go1PercentAPIAutomation/myPastSession/myPastSession.js
renamed the file in  camel case

2023-11-17 10:09 UTC, Ritika-gupta20 requested changes
Please copy the package.json from main and paste it to your branch and push it so that no changes are there

2023-11-17 10:09 UTC, Ritika-gupta20 commented on go1percent/package.json
please do not push changes in package.json on git

2023-11-17 10:55 UTC, Nituyadav0109 commented on go1percent/package.json
okay

2023-11-17 10:56 UTC, Ritika-gupta20 approved these changes

2023-11-17 11:18 UTC, deepansh257 approved these changes

2023-11-17 11:18 UTC, merged