Updated folder structure for API
NashTech-Labs/go1Percent_Automation pull request #106
Opened 2023-11-17 10:57 UTC by manas-NTech

2023-11-17 11:00 UTC, Ritika-gupta20 requested changes
Please move the image file to helpers under API/your module

2023-11-17 11:00 UTC, Ritika-gupta20 commented on go1percent/test/Go1PercentAPIAutomation/myProfile/KnoldusLogo.png
Please put this file in helpers folder under Go1PercentAPIAutomation->yourfolder->file.png

2023-11-17 11:06 UTC, manas-NTech commented on go1percent/test/Go1PercentAPIAutomation/myProfile/KnoldusLogo.png
Resolved.

2023-11-17 13:47 UTC, Ritika-gupta20 requested changes
Please move image to correct folder

2023-11-17 13:47 UTC, Ritika-gupta20 commented on go1percent/KnoldusLogo.png
Please put this file under the folder helpers->yourfolder->image.png

2023-11-20 07:44 UTC, manas-NTech commented on go1percent/KnoldusLogo.png
Updated.

2023-11-21 08:23 UTC, deepansh257 approved these changes

2023-11-22 09:30 UTC, Sparsh79 approved these changes

2023-11-22 09:44 UTC, Ritika-gupta20 approved these changes

2023-11-22 09:45 UTC, merged