Feature/leaderboard rewards part2
NashTech-Labs/go1Percent_Automation pull request #108
Opened 2023-11-20 06:50 UTC by ibrahimnadra

Removed assertions from page-objects.

2023-11-21 06:18 UTC, Ritika-gupta20 requested changes
Please make changes requested

2023-11-21 06:18 UTC, Ritika-gupta20 commented on go1percentTS/src/page-objects/Leaderboard_Rewards/add_reward.ts
Name of folder should be in camel casing only, please remove underscore

2023-11-22 08:28 UTC, Ritika-gupta20 approved these changes

2023-11-22 09:34 UTC, Sparsh79 approved these changes

2023-11-22 09:34 UTC, merged