Converted js testcases to ts for Techhub Employee User
NashTech-Labs/go1Percent_Automation pull request #111
Opened 2023-11-20 11:59 UTC by Anshika1603

2023-11-20 20:07 UTC, Sparsh79 commented on go1percentTS/src/page-objects/techhub/EmployeeUser/techhub.ts
> +    url: 'https://nashtechglobal.qa.go1percent.com',
Do we need to specify this here? I believe, even in POM this should be optional. Since you are providing the URL in beforeEach method, I don't think this is required here. Let me know if you think otherwise.

2023-11-21 06:02 UTC, Ritika-gupta20 approved these changes

2023-11-21 06:22 UTC, Anshika1603 commented on go1percentTS/src/page-objects/techhub/EmployeeUser/techhub.ts
> +    url: 'https://nashtechglobal.qa.go1percent.com',
Yes, removed url from POM.

2023-11-21 06:26 UTC, Anshika1603 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUser/TechhubEmployeeUser.ts
> +            .url("https://nashtechglobal.qa.go1percent.com")
sure, will make the changes when suitable.

2023-11-21 07:04 UTC, deepansh257 requested changes

2023-11-21 07:04 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUser/TechhubEmployeeUser.ts
> +            browser.expect.element('h6.mb-0.rank.status.approvedStatus').text.to.contain('Approved');
Remove selector from here. All selectors should be added in page object file and called from there in test file.

2023-11-21 07:08 UTC, Anshika1603 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUser/TechhubEmployeeUser.ts
> +            browser.expect.element('h6.mb-0.rank.status.approvedStatus').text.to.contain('Approved');
I tried, but it doesn't work when added in POM. So, need to declare it in test file only.

2023-11-21 08:29 UTC, Anshika1603 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUser/TechhubEmployeeUser.ts
> +            browser.expect.element('h6.mb-0.rank.status.approvedStatus').text.to.contain('Approved');
Tried to do that as well but elements method doesn't work in POM.

2023-11-21 08:38 UTC, deepansh257 approved these changes

2023-11-21 08:38 UTC, merged