TS FE added
NashTech-Labs/go1Percent_Automation pull request #112
Opened 2023-11-20 12:07 UTC by mansijain1knoldus

Added fe in Typescript

2023-11-20 20:17 UTC, Sparsh79 commented on go1percentTS/src/page-objects/RequestedSession/knolxRequestPage.ts
> +        descriptionInput: 'body > app-root > div > app-main > section > main > div > div > div > app-knolx > div > app-manage-session-detail > div.card.page-wrapper > div.row.manage-session-detail >
Please use a better locator strategy. Such long locators are not very dependable.

2023-11-21 08:26 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/RequestedSession/RequestedSessionsTest.ts
> +      .pause(500)
These pauses are very small, like half a second. Are you sure you even need these? Because if not, then we can remove them

2023-11-21 11:02 UTC, mansijain1knoldus commented on go1percentTS/src/test/Go1PercentFEAutomation/RequestedSession/RequestedSessionsTest.ts
> +      .pause(500)
done

2023-11-21 12:04 UTC, Ritika-gupta20 requested changes
Please make changes

2023-11-21 12:04 UTC, Ritika-gupta20 commented on go1percentTS/src/page-objects/RequestedSession/knolxRequestPage.ts
> +        descriptionInput: 'body > app-root > div > app-main > section > main > div > div > div > app-knolx > div > app-manage-session-detail > div.card.page-wrapper > div.row.manage-session-detail >
Please use specific classes for locators, these are too long

2023-11-21 12:04 UTC, Ritika-gupta20 commented on go1percentTS/src/page-objects/RequestedSession/knolxRequestPage.ts
> +            selector: "(//button[@class='btn btn-primary edit-session-button floatRight'][normalize-space()='Edit'])[2]",
same goes for these

2023-11-22 08:18 UTC, mansijain1knoldus commented on go1percentTS/src/page-objects/RequestedSession/knolxRequestPage.ts
> +            selector: "(//button[@class='btn btn-primary edit-session-button floatRight'][normalize-space()='Edit'])[2]",
Updated

2023-11-22 09:36 UTC, Sparsh79 commented on go1percentTS/src/test/Go1PercentFEAutomation/RequestedSession/RequestedSessionsTest.ts
> +  },
Can we have these test converted to "describe"  and "it" format please in this same PR?

2023-11-22 10:00 UTC, Sparsh79 approved these changes

2023-11-22 10:39 UTC, Ritika-gupta20 approved these changes

2023-11-23 07:23 UTC, merged