added frontend test cases in typescript
NashTech-Labs/go1Percent_Automation pull request #113
Opened 2023-11-21 06:02 UTC by Shrasti0207

2023-11-21 06:16 UTC, Ritika-gupta20 approved these changes

2023-11-21 07:12 UTC, Sparsh79 approved these changes

2023-11-21 07:16 UTC, deepansh257 requested changes

2023-11-21 07:16 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUserTest1.ts
> +                document.querySelector('textarea[formcontrolname="description"]')?.scrollIntoView();
Add locator in page object and call from there. Do not add locators in test file.

2023-11-21 07:16 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUserTest1.ts
> +            document.querySelector('select[id="category"]')?.scrollIntoView();
Create a reusable method to scroll to a particular element and use that everywhere needed

2023-11-21 08:18 UTC, Shrasti0207 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUserTest1.ts
> +                document.querySelector('textarea[formcontrolname="description"]')?.scrollIntoView();
querySelector is a core javascript method. Hence it is not picking the locators from POM

2023-11-21 09:39 UTC, Shrasti0207 commented on go1percentTS/src/test/Go1PercentFEAutomation/techhub/EmployeeUserTest1.ts
> +            document.querySelector('select[id="category"]')?.scrollIntoView();
we can not create a reusable method in POM of execute function

2023-11-22 08:34 UTC, deepansh257 approved these changes

2023-11-22 08:35 UTC, merged