Automated API of ticket assigned to me
NashTech-Labs/go1Percent_Automation pull request #12
Opened 2023-10-23 12:08 UTC by ajit1865

Automate the API's for feature tickets assigned to me.

2023-11-10 14:41 UTC, deepansh257 reviewed
Approved

2023-11-13 05:21 UTC, Sparsh79 commented
Approved.

2023-11-13 05:22 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
> +           args: ['--headless', '--no-sandbox']
Why you have added headless mode in default config, we already have dedicated env settings for headless chrome. Let's keep the default env basic(without any custom args)

2023-11-13 05:33 UTC, Ritika-gupta20 requested changes

2023-11-13 05:33 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
> +              '-headless',
Why here have you set this to headless again? This is the ticket for API and headless mode is not required. There are no changes needed in this file it you have taken pull from the main branch

2023-11-13 05:33 UTC, Ritika-gupta20 commented on go1percent/package-lock.json
Have you installed any new dependency? If not then why have you committed this file here.

2023-11-13 05:33 UTC, Ritika-gupta20 commented on nightwatch.conf.js
Why do we have two config file? Config should only exist inside go1percent directory

2023-11-13 06:43 UTC, Sparsh79 approved these changes

2023-11-13 06:57 UTC, ajit1865 commented on go1percent/package-lock.json
i update this code from main so I commit it

2023-11-13 06:58 UTC, ajit1865 commented on nightwatch.conf.js
Removed another config file

2023-11-13 06:59 UTC, ajit1865 commented on go1percent/nightwatch.conf.js
> +              '-headless',
my code throws some error when running via headless like chrome session so I made this changes

2023-11-15 06:38 UTC, Ritika-gupta20 approved these changes

2023-11-15 07:07 UTC, deepansh257 approved these changes

2023-11-15 07:07 UTC, merged