Feature/setting api
NashTech-Labs/go1Percent_Automation pull request #122
Opened 2023-11-21 14:20 UTC by souravmishraa

added apipart

2023-11-22 08:16 UTC, Ritika-gupta20 commented on go1percent/package-lock.json
Please remove this

2023-11-22 08:16 UTC, Ritika-gupta20 commented on go1percent/page-objects/settingPage.js
please make a folder of your feature and move it there

2023-11-22 08:16 UTC, Ritika-gupta20 commented on go1percent/test/Setting/settingapi.js
please move your feature folder in Go1PercentAPIAutomation

2023-11-22 08:16 UTC, Ritika-gupta20 commented on go1percent/test/Setting/settingapi.js
> +      .send({ "name": "Test Employeeet", "email": "testemployee@nashtechglobal.com" })
use globals.js for this

2023-11-23 07:31 UTC, deepansh257 requested changes

2023-11-23 07:31 UTC, deepansh257 commented on go1percent/page-objects/settingPage/settingPage.js
> +        fullName:"body > app-root > div > app-main > section > main > div > div > div > app-my-profile > div > div.col-lg-8 > div:nth-child(3) > app-my-settings > div > div.float-container > div > di
Most of these locators are incorrect. All locators starting from body or html are absolute and should not be used. Please replace with relative locators.

2023-11-23 07:31 UTC, deepansh257 commented on go1percent/page-objects/settingPage/settingPage.js
> +                  .pause(5000)
Use wait commands instead of pauses.

2023-11-23 07:31 UTC, deepansh257 commented on go1percent/page-objects/settingPage/settingPage.js
> +        //  .pause(5000)
Remove commented code if not needed

2023-11-23 07:31 UTC, deepansh257 commented on go1percent/test/Go1PercentFEAutomation/setting/setting.js
> +        .pause(2000)
Too many unnessary pauses. Please remove and replace with wait commands if needed

2023-11-28 06:50 UTC, closed without merging

2023-11-28 06:51 UTC, Ritika-gupta20 commented
Please make a PR again, this one contains package-lock.json, gitignore. Kindly do not commit such files that were requested earlier in group