Frontend testcases with typescript for my profile module
NashTech-Labs/go1Percent_Automation pull request #127
Opened 2023-11-22 08:35 UTC by manas-NTech

Added all frontend testcases with typescript.

2023-11-22 09:45 UTC, Sparsh79 commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.js
> +Object.defineProperty(exports, "__esModule", { value: true });
What's this line of code doing?

2023-11-22 09:46 UTC, Sparsh79 commented on nightwatch.conf.js
> +//
Please do not commit the conf file. Please revert back the changes.

2023-11-22 09:47 UTC, Sparsh79 commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_UI.ts
> +// password = 'testemployee';
Please remove the commented line of code, applicable to all the files.

2023-11-22 10:50 UTC, Ritika-gupta20 commented on nightwatch.conf.js
This file is outside the go1percent, please delete it

2023-11-23 05:04 UTC, manas-NTech commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.js
> +Object.defineProperty(exports, "__esModule", { value: true });
This is the auto generated code from the respective ts file, removed it.

2023-11-23 05:07 UTC, manas-NTech commented on nightwatch.conf.js
File deleted.

2023-11-23 05:08 UTC, manas-NTech commented on nightwatch.conf.js
> +//
Updated.

2023-11-23 07:55 UTC, deepansh257 requested changes

2023-11-23 07:55 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_UI.ts
> +        browser.elements('xpath', "//div[@class='w-20']", function (result) {
Move all locators from test file to page object file

2023-11-23 07:55 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.ts
> +            .pause(8000)
Remove these many pauses with wait commands

2023-11-23 07:55 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.ts
> +//const MyProfilePage = require('../../page-objects/myProfilePage');
remove commented code if not needed

2023-11-23 07:55 UTC, deepansh257 commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.js
> +Object.defineProperty(exports, "__esModule", { value: true });
File still not removed

2023-11-23 07:55 UTC, deepansh257 commented on nightwatch.conf.js
> +//
File still not removed

2023-11-23 08:11 UTC, manas-NTech commented on go1percentTS/src/page-objects/myProfile/myProfilePage.ts
> +        BadgeMonth: "div[class='modal-body m-2 p-4'] div:nth-child(1) div:nth-child(1) h6:nth-child(1)",
Updated for locators.

2023-11-23 14:42 UTC, manas-NTech commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.js
> +Object.defineProperty(exports, "__esModule", { value: true });
File removed.

2023-11-23 14:49 UTC, manas-NTech commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_UI.ts
> +        browser.elements('xpath', "//div[@class='w-20']", function (result) {
Locators moved to page-object file

2023-11-23 14:49 UTC, manas-NTech commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.ts
> +            .pause(8000)
Implemented with wait commands.

2023-11-23 14:50 UTC, manas-NTech commented on go1percentTS/src/test/Go1PercentFEAutomation/myProfile/myProfile_AdminUser_UI.ts
> +//const MyProfilePage = require('../../page-objects/myProfilePage');
Removed commented code.

2023-11-24 08:33 UTC, Ritika-gupta20 commented on go1percentTS/nightwatch.conf.js
config file not to be committed, please remove

2023-11-24 08:33 UTC, Ritika-gupta20 commented on go1percentTS/src/page-objects/myProfile/myProfilePage.ts
> +                .waitForElementVisible('@NoBadgeEarned', 30000)
I think here we need to make the interface for commands and elements and then export them to use in test file. Please make appropriate changes , as this will create errors in running other scripts

2023-11-26 10:19 UTC, manas-NTech commented on go1percentTS/nightwatch.conf.js
committed config file removed.

2023-11-26 10:20 UTC, manas-NTech commented on go1percentTS/src/page-objects/myProfile/myProfilePage.ts
> +                .waitForElementVisible('@NoBadgeEarned', 30000)
Updated.

2023-11-28 04:22 UTC, manas-NTech commented on nightwatch.conf.js
> +//
File removed.

2023-11-28 06:41 UTC, Ritika-gupta20 approved these changes

2023-11-28 06:42 UTC, deepansh257 approved these changes

2023-11-28 06:42 UTC, merged