Added FE TCs in typescript.
NashTech-Labs/go1Percent_Automation pull request #132
Opened 2023-11-22 11:56 UTC by JuliKumari-NashTech

2023-11-22 13:03 UTC, Ritika-gupta20 requested changes

2023-11-22 13:03 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
please give path of page object in test file correctly so that you can use page-objects directly

2023-11-22 13:03 UTC, Ritika-gupta20 commented on go1percent/page-objects/login.js
> +    url: "",
please don't make changes in files that are used by other features

2023-11-22 13:03 UTC, Ritika-gupta20 commented on go1percentTS/nightwatch.conf.js
> +  page_objects_path: ['./dist/src/page-objects','./dist/src/page-objects/knolxSessions'],
Please give appropriate path for page-object in your test file and do not make changes in config files. please revert the changes.

2023-11-22 14:22 UTC, JuliKumari-NashTech commented on go1percent/nightwatch.conf.js
okay sure , i have changed this.

2023-11-22 14:29 UTC, JuliKumari-NashTech commented on go1percent/page-objects/login.js
> +    url: "",
sure @Ritika-gupta20

2023-11-23 07:34 UTC, Ritika-gupta20 approved these changes

2023-11-23 07:35 UTC, Sparsh79 approved these changes

2023-11-23 07:35 UTC, merged