My Profile Front End Automation
NashTech-Labs/go1Percent_Automation pull request #65
Opened 2023-11-07 08:02 UTC by manas-NTech

Segregate front End Automation.

2023-11-13 06:53 UTC, Sparsh79 commented on go1percent/page-objects/My_Profile/myProfilePage.js
> +            selector: "//body/app-root/div/app-main/section[@class='g-sidenav-show']/main[@class='main-content position-relative max-height-vh-100 h-100 border-radius-lg']/div[@class='container-fluid
Please use a better locator strategy. Do not use absolute xpaths.

2023-11-13 07:11 UTC, manas-NTech commented on go1percent/page-objects/My_Profile/myProfilePage.js
> +            selector: "//body/app-root/div/app-main/section[@class='g-sidenav-show']/main[@class='main-content position-relative max-height-vh-100 h-100 border-radius-lg']/div[@class='container-fluid
Updated all the absolute xpath to css selector.

2023-11-13 08:09 UTC, deepansh257 requested changes

2023-11-13 08:09 UTC, deepansh257 commented on go1percent/test/myProfile_FE/myProfile.js
> +            .pause(7000)
Too many pause commands. Please remove and use wait commands

2023-11-13 08:09 UTC, deepansh257 commented on go1percent/test/myProfile_FE/myProfile.js
> +        browser.elements('xpath', "//div[@class='w-20']", function (result) {
Do not put any locator in test file. Add all of them in page object and call from there.

2023-11-13 08:26 UTC, Sparsh79 approved these changes

2023-11-13 08:30 UTC, deepansh257 requested changes

2023-11-13 08:30 UTC, deepansh257 commented on go1percent/test/myProfile_FE/myProfile.js
> +        browser.elements('xpath', "//div[@class='w-20']", function (result) {
put all the locators from test file in page object file

2023-11-15 05:32 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
> -  page_objects_path: ['page-objects', 'page-objects/Techhub_AdminUser_FE'],
Why have you deleted this, please add for your module and do not delete other module code from anywhere

2023-11-15 05:34 UTC, Ritika-gupta20 requested changes
Please do the changes in config.js, do not remove code of other modules

2023-11-15 05:34 UTC, Ritika-gupta20 commented
Please resolve conflicts

2023-11-16 11:37 UTC, manas-NTech commented on go1percent/nightwatch.conf.js
> -  page_objects_path: ['page-objects', 'page-objects/Techhub_AdminUser_FE'],
Added my page-objects path.

2023-11-16 12:49 UTC, Ritika-gupta20 approved these changes

2023-11-16 12:49 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
> -  page_objects_path: ['page-objects', 'page-objects/Techhub_AdminUser_FE'],
please don't remove others code and replace it with yours

2023-11-16 12:59 UTC, deepansh257 approved these changes

2023-11-16 12:59 UTC, merged