adding my FE test cases
NashTech-Labs/go1Percent_Automation pull request #68
Opened 2023-11-07 13:11 UTC by RahulKnolder

added FE test cases

2023-11-13 07:00 UTC, Sparsh79 commented on go1percent/page-objects/LeaderBoard_Summary/summary.js
> +                    .assert.containsText('@contributionTypes_2', 'Online Courses')
We should be asserting in the test file itself, not here.

2023-11-13 07:02 UTC, Sparsh79 commented on go1percent/page-objects/LeaderBoard_Summary/summary.js
> +                    .assert.containsText('@contributionTypes_2', 'Online Courses')
Rest LGTM!

2023-11-15 05:46 UTC, Ritika-gupta20 commented on go1percent/globals.js
> -
Please put it outside admin block, this for adminuser for techhub module. create a separate block for your module under globals.js

2023-11-15 05:47 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
> -  page_objects_path: ['page-objects', 'page-objects/Techhub_AdminUser_FE'],
Please do not remove other module code form anywhere, keep it as it is. It will not effect your script to run

2023-11-15 05:48 UTC, Ritika-gupta20 commented on go1percent/package.json
> -    "validator": "^13.11.0",
Please do not remove the dependencies that were already there in the file

2023-11-15 05:48 UTC, Ritika-gupta20 requested changes
Please work on the comments, also there are conflicts so take a pull from main and resolve the conflicts. You can also copy the code from main of these files and paste them to resolve conflicts

2023-11-16 12:26 UTC, closed without merging