Refactored test cases for image upload
NashTech-Labs/go1Percent_Automation pull request #82
Opened 2023-11-13 07:28 UTC by vanshika1221

Deleted duplicate folders 
Refactored test cases for image upload

2023-11-13 07:36 UTC, Sparsh79 approved these changes

2023-11-13 08:11 UTC, deepansh257 requested changes

2023-11-13 08:11 UTC, deepansh257 commented on go1percent/test/Leaderboard_Reward_Part1/Rewards_UI/Leaderboard_UI_Admin.js
> +                .isEnabled('div.ImageMinWidthClass > input', function () {
Do not add loctors in test file. Instead add them in page object files and call from there. Do this for all such locators.

2023-11-13 08:20 UTC, vanshika1221 commented on go1percent/test/Leaderboard_Reward_Part1/Rewards_UI/Leaderboard_UI_Admin.js
> +                .isEnabled('div.ImageMinWidthClass > input', function () {
but for browser, locators are not working from the page object

2023-11-15 05:56 UTC, Ritika-gupta20 requested changes
Please work on the comments

2023-11-15 05:56 UTC, Ritika-gupta20 commented on go1percent/nightwatch.conf.js
> -      "userName": "testemployee", // this is placeholder username, make sure to update.
Please do not remove testemployee form here, better would be give a different name for your module like adminUser has given. This will effect other people code.

2023-11-15 05:56 UTC, Ritika-gupta20 commented on go1percent/test/Go1PercentFEAutomation/Leaderboard_Rewards_Part1/Leaderboard_UI_Admin.js
Why have you named it as Part 1? If two people are working on this module and tests are divided then please rename the test file as 1 and 2.

2023-11-16 06:42 UTC, deepansh257 approved these changes

2023-11-16 08:52 UTC, Ritika-gupta20 approved these changes

2023-11-16 08:52 UTC, merged