Feature/leaderboard rewards part2
NashTech-Labs/go1Percent_Automation pull request #83
Opened 2023-11-13 07:31 UTC by ibrahimnadra

1. Reorganised the folder structure.
2. Renamed the folder.
3. Modified the fe test cases and page objects.

2023-11-15 06:00 UTC, Ritika-gupta20 requested changes
Please do the changes as per comments

2023-11-15 06:00 UTC, Ritika-gupta20 commented on go1percent/test/Go1PercentFEAutomation/Leaderboard_rewards_part2/AddRewardTest.js
Please add these test in one folder names as Leaderboard_rewards, under that the test file may contain 1 or 2 in the name to differentiate

2023-11-16 06:03 UTC, ibrahimnadra commented on go1percent/test/Go1PercentAPIAutomation/Leaderboard_rewards_part2/RedeemRewardTest.js
Done

2023-11-16 09:01 UTC, Ritika-gupta20 approved these changes

2023-11-16 09:01 UTC, Ritika-gupta20 commented on go1percent/helpers/Go1PercentFEAutomation/TECHHUB/AdminUser/go1PercentTechhub.js
> -
Why any change is done here in other module

2023-11-16 12:56 UTC, deepansh257 requested changes

2023-11-16 12:56 UTC, deepansh257 commented on go1percent/helpers/Go1PercentFEAutomation/LeaderboardRewards/helperFunctions.js
> +    for (let i = 1; i < 6; i++) {
Do not use variable names like i, j, k. Instead give meaningful names

2023-11-16 12:56 UTC, deepansh257 commented on go1percent/test/Go1PercentAPIAutomation/LeaderboardRewards/RedeemRewardTest.js
> +  //       .then(function (response) {
Remove this code if not needed. Else uncomment it if useful

2023-11-16 15:15 UTC, Sparsh79 approved these changes

2023-11-16 17:36 UTC, merged