Feature/new knolx sessions frontend automation testing
NashTech-Labs/go1Percent_Automation pull request #86
Opened 2023-11-13 09:12 UTC by JuliKumari-NashTech

2023-11-15 06:16 UTC, Ritika-gupta20 approved these changes

2023-11-16 08:58 UTC, Ritika-gupta20 requested changes
Camel casing to be used to name folders

2023-11-16 08:58 UTC, Ritika-gupta20 commented on go1percent/test/Go1PercentFEAutomation/KNOLXSESSIONS/knolxSessions.js
Name of folder to be in camel case

2023-11-16 08:58 UTC, Ritika-gupta20 commented on go1percent/test/Go1PercentAPIAutomation/KNOLXSESSIONS/knolxSessions.js
Name of folder to be in camel case

2023-11-16 12:21 UTC, JuliKumari-NashTech commented on go1percent/test/Go1PercentFEAutomation/KNOLXSESSIONS/knolxSessions.js
changes done

2023-11-17 10:12 UTC, Ritika-gupta20 approved these changes

2023-11-17 10:13 UTC, Ritika-gupta20 commented
conflicts in conf.js

2023-11-20 20:20 UTC, Sparsh79 approved these changes

2023-11-21 05:59 UTC, JuliKumari-NashTech commented
> conflicts in conf.js

2023-11-21 06:00 UTC, JuliKumari-NashTech commented
resolved conflict

2023-11-21 06:59 UTC, merged