Feature/requested session
NashTech-Labs/go1Percent_Automation pull request #99
Opened 2023-11-15 10:41 UTC by mansijain1knoldus

updated folder structure

2023-11-16 09:03 UTC, Ritika-gupta20 requested changes
Please use camel case to name your folders

2023-11-16 09:13 UTC, Ritika-gupta20 commented on go1percent/page-objects/REQUESTED_SESSION/knolxRequestPage.js
Please rename the folder using camel casing

2023-11-16 09:50 UTC, mansijain1knoldus commented on go1percent/page-objects/REQUESTED_SESSION/knolxRequestPage.js
Done

2023-11-17 11:42 UTC, Ritika-gupta20 approved these changes

2023-11-17 13:31 UTC, deepansh257 approved these changes

2023-11-17 13:32 UTC, merged